---
- name: Copy nginx.conf to server
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Update upstreams
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf owner=root group=root mode=0644

- name: Restart nginx
  service: name=nginx state=restarted
