---
- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

  tasks:
    - name: Ensure NTP is installed
      apt: name=ntp state=present

    - name: Ensure NTP is running
      service: name=ntp state=started
