---
- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

  tasks:
    - name: Ensure nginx is installed
      apt: name=nginx state=present

    - name: Ensure nginx is running
      service: name=nginx state=started
